### ISSUE TITLE
Comments don't work

### ISSUE THREAD

**Issue by diplomod** [diplomod/WellBet-App#48]
I cannot place a comment
![2014-12-26 18 52 32](https://cloud.githubusercontent.com/assets/7487883/5558787/91c22b06-8d34-11e4-9db9-15a4621a3f27.png)

**Comment by mladenbl** [comment]
We will need access to wordpress plugins files used on website because they making problems in API. For ex. that problem with comments are caused by flamingo plugin and this code:

// GEONOVA-EDIT
$gn_filter = $args['gn_flamingo_filter'];

I'm getting "Undefined index: gn_flamingo_filter" error.

I will not modify any files used by plugin, i just need to see how it's working and how can i solve that problem in API(i will disable some actions, filters etc. in api request).

**Comment by diplomod** [comment]
I forwarded this info to the programming team of geonova.no

**Comment by Immoz** [comment]
Hi, i tried to fix this line in the flamingo plugin. Does it work now?

**Comment by diplomod** [comment]
Thanks a ot. However, does not work in the app yet.
![2014-12-29 19 53 32](https://cloud.githubusercontent.com/assets/7487883/5572957/c5390112-8fa5-11e4-803d-0ddcc23307d4.png)

**Comment by Immoz** [comment]
Is the error still caused by the flamingo plugin and this error message?
"Undefined index: gn_flamingo_filter"

Normally this should not happen anymore.

**Comment by mladjan** [comment]
I tested it right now, it works.

**Comment by diplomod** [comment]
Same still. Tried with 2 different users on all WellBets.
![2015-01-05 15 20 04](https://cloud.githubusercontent.com/assets/7487883/5614675/c51c864c-94f3-11e4-9f36-fb66549c6846.png)
![2015-01-05 15 48 24](https://cloud.githubusercontent.com/assets/7487883/5614682/cfbff9da-94f3-11e4-8cb7-dd57c5632771.png)

**Comment by mladenbl** [comment]
Fixed, problem with new plugin in wordpress, i just removed all save_post actions on comments submit(in api) and you will not have problem with this again.

**Comment by diplomod** [comment]
Well, I hate to tell you, but I do: Still can't comment. Anywhere... Tried all bets and different users.
![2015-01-06 20 44 21](https://cloud.githubusercontent.com/assets/7487883/5635349/ab5000e0-95e8-11e4-8004-8cd5799832d3.png)
![2015-01-06 20 48 06](https://cloud.githubusercontent.com/assets/7487883/5635352/b260916a-95e8-11e4-995a-5ca50ea54382.png)

**Comment by diplomod** [comment]
I saw that Audrius was able to comment. He has an iPhone 5c. I use iPhone 4. Maybe it's an issue with older versions of the iPhone?

**Comment by mladjan** [comment]
There is no difference between different types of device, this can be up to your account.
On my phone, it works every time.
Can you tell me which account you are using so I can log in and try in debug environment?

**Comment by diplomod** [comment]
Two accounts:
diplomod@gmail.com / 12345
hans_gebauer@hotmail.com / 123456

**Comment by mladjan** [comment]
Thx, something crashes on the server with your account, I just sent this to
Mladen our developer (right now is Christmas for him, maybe he will respond
tomorrow).

**Comment by diplomod** [comment]
OK  -I just created a new account - it works! So I guess this is fine. :)
